--------------------------------------------------------
--  Arquivo criado - quarta-feira-outubro-16-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLIENTES_ID_CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."CLIENTES_ID_CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CONSTATOS_ID_CONTATO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."CONSTATOS_ID_CONTATO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence C_P_ID_CP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."C_P_ID_CP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAGAMENTOS_ID_PAGAMENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."PAGAMENTOS_ID_PAGAMENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence S_C_ID_SC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."S_C_ID_SC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEGUROS_ID_SEGURO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."SEGUROS_ID_SEGURO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."SEQ_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CONTATOS
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."SEQ_CONTATOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ENDERECOS
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."SEQ_ENDERECOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence S_P_ID_SP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PAULO"."S_P_ID_SP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "PAULO"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER, 
	"TIPO_CLIENTE" VARCHAR2(20 BYTE), 
	"NOME" VARCHAR2(100 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"NUMERO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"DATA_NASCIMENTO" VARCHAR2(10 BYTE), 
	"ENDERECOS_ID_ENDERECO" NUMBER, 
	"CONTATOS_ID_CONTATO" NUMBER, 
	"S_C_ID_SC" NUMBER, 
	"C_P_ID_CP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTATOS
--------------------------------------------------------

  CREATE TABLE "PAULO"."CONTATOS" 
   (	"ID_CONTATO" NUMBER, 
	"TELEFONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CONTATO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table C_P
--------------------------------------------------------

  CREATE TABLE "PAULO"."C_P" 
   (	"ID_CP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENDERECOS
--------------------------------------------------------

  CREATE TABLE "PAULO"."ENDERECOS" 
   (	"ID_ENDERECO" NUMBER, 
	"NUMERO" NUMBER(5,0), 
	"CEP" VARCHAR2(10 BYTE), 
	"LOGRADOURO" VARCHAR2(100 BYTE), 
	"BAIRRO" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(50 BYTE), 
	"COMPLEMENTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGAMENTOS
--------------------------------------------------------

  CREATE TABLE "PAULO"."PAGAMENTOS" 
   (	"ID_PAGAMENTO" NUMBER, 
	"DATA_PAGAMENTO" VARCHAR2(10 BYTE), 
	"TIPO_PAGAMENTO" VARCHAR2(30 BYTE), 
	"FORMA_PAGAMENTO" VARCHAR2(50 BYTE), 
	"PARCELAS" VARCHAR2(5 BYTE), 
	"VALOR_PARCELA" NUMBER, 
	"DESCONTO" NUMBER, 
	"VALOR_TOTAL" NUMBER, 
	"S_P_ID_SP" NUMBER, 
	"C_P_ID_CP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table S_C
--------------------------------------------------------

  CREATE TABLE "PAULO"."S_C" 
   (	"ID_SC" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEGUROS
--------------------------------------------------------

  CREATE TABLE "PAULO"."SEGUROS" 
   (	"ID_SEGURO" NUMBER, 
	"TIPO" VARCHAR2(50 BYTE), 
	"PERFIL" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER, 
	"S_C_ID_SC" NUMBER, 
	"S_P_ID_SP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table S_P
--------------------------------------------------------

  CREATE TABLE "PAULO"."S_P" 
   (	"ID_SP" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into PAULO.CLIENTES
SET DEFINE OFF;
REM INSERTING into PAULO.CONTATOS
SET DEFINE OFF;
REM INSERTING into PAULO.C_P
SET DEFINE OFF;
REM INSERTING into PAULO.ENDERECOS
SET DEFINE OFF;
REM INSERTING into PAULO.PAGAMENTOS
SET DEFINE OFF;
REM INSERTING into PAULO.S_C
SET DEFINE OFF;
REM INSERTING into PAULO.SEGUROS
SET DEFINE OFF;
REM INSERTING into PAULO.S_P
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."CLIENTES_PK" ON "PAULO"."CLIENTES" ("ID_CLIENTE", "S_C_ID_SC", "C_P_ID_CP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONSTATOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."CONSTATOS_PK" ON "PAULO"."CONTATOS" ("ID_CONTATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index S_P_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."S_P_PK" ON "PAULO"."S_P" ("ID_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEGUROS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."SEGUROS_PK" ON "PAULO"."SEGUROS" ("ID_SEGURO", "S_C_ID_SC", "S_P_ID_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENDERECOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."ENDERECOS_PK" ON "PAULO"."ENDERECOS" ("ID_ENDERECO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index S_C_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."S_C_PK" ON "PAULO"."S_C" ("ID_SC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index C_P_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."C_P_PK" ON "PAULO"."C_P" ("ID_CP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAGAMENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAULO"."PAGAMENTOS_PK" ON "PAULO"."PAGAMENTOS" ("ID_PAGAMENTO", "S_P_ID_SP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CLIENTES_ID_CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."CLIENTES_ID_CLIENTE_TRG" BEFORE
    INSERT ON clientes
    FOR EACH ROW
     WHEN ( new.id_cliente IS NULL ) BEGIN
    :new.id_cliente := clientes_id_cliente_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."CLIENTES_ID_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONSTATOS_ID_CONTATO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."CONSTATOS_ID_CONTATO_TRG" BEFORE
    INSERT ON "CONTATOS"
    FOR EACH ROW
     WHEN ( new.id_contato IS NULL ) BEGIN
    :new.id_contato := constatos_id_contato_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."CONSTATOS_ID_CONTATO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger C_P_ID_CP_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."C_P_ID_CP_TRG" BEFORE
    INSERT ON c_p
    FOR EACH ROW
     WHEN ( new.id_cp IS NULL ) BEGIN
    :new.id_cp := c_p_id_cp_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."C_P_ID_CP_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAGAMENTOS_ID_PAGAMENTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."PAGAMENTOS_ID_PAGAMENTO_TRG" BEFORE
    INSERT ON pagamentos
    FOR EACH ROW
     WHEN ( new.id_pagamento IS NULL ) BEGIN
    :new.id_pagamento := pagamentos_id_pagamento_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."PAGAMENTOS_ID_PAGAMENTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger S_C_ID_SC_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."S_C_ID_SC_TRG" BEFORE
    INSERT ON s_c
    FOR EACH ROW
     WHEN ( new.id_sc IS NULL ) BEGIN
    :new.id_sc := s_c_id_sc_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."S_C_ID_SC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SEGUROS_ID_SEGURO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."SEGUROS_ID_SEGURO_TRG" BEFORE
    INSERT ON seguros
    FOR EACH ROW
     WHEN ( new.id_seguro IS NULL ) BEGIN
    :new.id_seguro := seguros_id_seguro_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."SEGUROS_ID_SEGURO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger S_P_ID_SP_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PAULO"."S_P_ID_SP_TRG" BEFORE
    INSERT ON s_p
    FOR EACH ROW
     WHEN ( new.id_sp IS NULL ) BEGIN
    :new.id_sp := s_p_id_sp_seq.nextval;
END;
/
ALTER TRIGGER "PAULO"."S_P_ID_SP_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ENDERECOS
--------------------------------------------------------

  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("ID_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("CEP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("LOGRADOURO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("BAIRRO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" MODIFY ("COMPLEMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."ENDERECOS" ADD CONSTRAINT "ENDERECOS_PK" PRIMARY KEY ("ID_ENDERECO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table S_P
--------------------------------------------------------

  ALTER TABLE "PAULO"."S_P" MODIFY ("ID_SP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."S_P" ADD CONSTRAINT "S_P_PK" PRIMARY KEY ("ID_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("TIPO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("NUMERO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("ENDERECOS_ID_ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("CONTATOS_ID_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("S_C_ID_SC" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" MODIFY ("C_P_ID_CP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID_CLIENTE", "S_C_ID_SC", "C_P_ID_CP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table C_P
--------------------------------------------------------

  ALTER TABLE "PAULO"."C_P" MODIFY ("ID_CP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."C_P" ADD CONSTRAINT "C_P_PK" PRIMARY KEY ("ID_CP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table S_C
--------------------------------------------------------

  ALTER TABLE "PAULO"."S_C" MODIFY ("ID_SC" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."S_C" ADD CONSTRAINT "S_C_PK" PRIMARY KEY ("ID_SC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTATOS
--------------------------------------------------------

  ALTER TABLE "PAULO"."CONTATOS" MODIFY ("ID_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CONTATOS" MODIFY ("TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CONTATOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CONTATOS" MODIFY ("CONTATO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."CONTATOS" ADD CONSTRAINT "CONSTATOS_PK" PRIMARY KEY ("ID_CONTATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGAMENTOS
--------------------------------------------------------

  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("ID_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("DATA_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("TIPO_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("FORMA_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("PARCELAS" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("VALOR_PARCELA" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("DESCONTO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("S_P_ID_SP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" MODIFY ("C_P_ID_CP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."PAGAMENTOS" ADD CONSTRAINT "PAGAMENTOS_PK" PRIMARY KEY ("ID_PAGAMENTO", "S_P_ID_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEGUROS
--------------------------------------------------------

  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("ID_SEGURO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("S_C_ID_SC" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" MODIFY ("S_P_ID_SP" NOT NULL ENABLE);
  ALTER TABLE "PAULO"."SEGUROS" ADD CONSTRAINT "SEGUROS_PK" PRIMARY KEY ("ID_SEGURO", "S_C_ID_SC", "S_P_ID_SP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "PAULO"."CLIENTES" ADD CONSTRAINT "CLIENTES_C_P_FK" FOREIGN KEY ("C_P_ID_CP")
	  REFERENCES "PAULO"."C_P" ("ID_CP") ENABLE;
  ALTER TABLE "PAULO"."CLIENTES" ADD CONSTRAINT "CLIENTES_CONTATOS_FK" FOREIGN KEY ("CONTATOS_ID_CONTATO")
	  REFERENCES "PAULO"."CONTATOS" ("ID_CONTATO") ENABLE;
  ALTER TABLE "PAULO"."CLIENTES" ADD CONSTRAINT "CLIENTES_ENDERECOS_FK" FOREIGN KEY ("ENDERECOS_ID_ENDERECO")
	  REFERENCES "PAULO"."ENDERECOS" ("ID_ENDERECO") ENABLE;
  ALTER TABLE "PAULO"."CLIENTES" ADD CONSTRAINT "CLIENTES_S_C_FK" FOREIGN KEY ("S_C_ID_SC")
	  REFERENCES "PAULO"."S_C" ("ID_SC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGAMENTOS
--------------------------------------------------------

  ALTER TABLE "PAULO"."PAGAMENTOS" ADD CONSTRAINT "PAGAMENTOS_C_P_FK" FOREIGN KEY ("C_P_ID_CP")
	  REFERENCES "PAULO"."C_P" ("ID_CP") ENABLE;
  ALTER TABLE "PAULO"."PAGAMENTOS" ADD CONSTRAINT "PAGAMENTOS_S_P_FK" FOREIGN KEY ("S_P_ID_SP")
	  REFERENCES "PAULO"."S_P" ("ID_SP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEGUROS
--------------------------------------------------------

  ALTER TABLE "PAULO"."SEGUROS" ADD CONSTRAINT "SEGUROS_S_C_FK" FOREIGN KEY ("S_C_ID_SC")
	  REFERENCES "PAULO"."S_C" ("ID_SC") ENABLE;
  ALTER TABLE "PAULO"."SEGUROS" ADD CONSTRAINT "SEGUROS_S_P_FK" FOREIGN KEY ("S_P_ID_SP")
	  REFERENCES "PAULO"."S_P" ("ID_SP") ENABLE;
